/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PayPal;

import java.awt.Color;
import static java.awt.Color.red;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */

public class jFrameNewAccount extends javax.swing.JFrame {

    private static String username;
    private static String userpassword;
    private static int ages;
    private static String gender;
    private static String address;
    private static String dob;
    
    public jFrameNewAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_dob = new javax.swing.JPanel();
        jTextField_username = new javax.swing.JTextField();
        jTextField_ages = new javax.swing.JTextField();
        jCheckBox = new javax.swing.JCheckBox();
        jBtn_setup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jTextField_dob = new javax.swing.JTextField();
        jBtn_goback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_dob.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_dob.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jPanel_dob.setFocusable(false);

        jTextField_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_username.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username/Number/Email", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jTextField_ages.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_ages.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_ages.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ages", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox.setText(" Check Box");
        jCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jBtn_setup.setBackground(new java.awt.Color(51, 51, 255));
        jBtn_setup.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jBtn_setup.setForeground(new java.awt.Color(255, 255, 255));
        jBtn_setup.setText("Set Up");
        jBtn_setup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_setupActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents\\Apache NetBeans\\CourseWork\\Image\\paypal logo.png")); // NOI18N

        jTextField_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_password.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jTextField_address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_address.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jComboBox_gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox_gender.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jTextField_dob.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_dob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_dob.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date Of Birth", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jBtn_goback.setBackground(new java.awt.Color(204, 204, 255));
        jBtn_goback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtn_goback.setText("<< Back");
        jBtn_goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_gobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_dobLayout = new javax.swing.GroupLayout(jPanel_dob);
        jPanel_dob.setLayout(jPanel_dobLayout);
        jPanel_dobLayout.setHorizontalGroup(
            jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dobLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_dobLayout.createSequentialGroup()
                        .addComponent(jTextField_ages, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_dobLayout.createSequentialGroup()
                        .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_dobLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel_dobLayout.createSequentialGroup()
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_dobLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_dobLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jBtn_goback)
                        .addGap(81, 81, 81)
                        .addComponent(jBtn_setup, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel_dobLayout.setVerticalGroup(
            jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_dobLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_dob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ages, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel_dobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_setup, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_goback, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_setupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_setupActionPerformed
        // check the input jtextfield is empty or not and show the message dailog
        if (jTextField_username.getText().isEmpty() && jTextField_ages.getText().isEmpty() || jCheckBox.getText().isEmpty() && 
            jTextField_ages.getText().isEmpty() && jComboBox_gender.getSelectedItem() != null && jTextField_address.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Please field the details!!");
            
        }else if(jTextField_username.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "The username is empty!");
        }else if(jTextField_password.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "The password is empty!");
        }else if(jTextField_ages.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "The ages is empty!");
        }else if(jComboBox_gender.getSelectedItem() == null){
            JOptionPane.showMessageDialog(rootPane, "The gender is empty!");
        }else if(jTextField_address.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "The address is empty!");
        }else{
            // using the try catch and find the exception
            try{
                // user input values
                username = jTextField_username.getText();
                userpassword = jTextField_ages.getText();
                ages = Integer.parseInt(jTextField_ages.getText());
                gender = jComboBox_gender.getSelectedItem().toString();
                address = jTextField_address.getText();
                dob = jTextField_dob.getText();
                
                //display the new users details
                JOptionPane.showMessageDialog(rootPane, "Username: "+username+"\nPassword: "+userpassword+"\nAges: "+ages+"\nGender: "+gender+"\nAddress: "+address+"\nDateOfBirth: "+dob);
                // set the boolean variable's values
                jFrameHomePage homepage = new jFrameHomePage();
                homepage.setVisible(true);
                dispose();
                
            }catch(HeadlessException | NumberFormatException ex){
                // invalid input then the input data's color is change
                jTextField_ages.setForeground(Color.red);
                JOptionPane.showMessageDialog(rootPane, "Enter the valid input!");
            }
            //JOptionPane.showMessageDialog(rootPane, "Enter the login button");
        }

        //       if(regist==true){
            //            //create an object and to the next page
            //            NewJFrame jf = new NewJFrame();
            //            dispose();
            //            jf.setVisible(true);
            //        }else{
            //            JOptionPane.showMessageDialog(rootPane, "Please register first");
            //        }
    }//GEN-LAST:event_jBtn_setupActionPerformed

    private void jBtn_gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_gobackActionPerformed
        jBtn_goback.setBackground(new Color(0,0,255));
        // create an object of kogin page the setVisible
        jFrameLoginPage loginpage = new jFrameLoginPage();
        loginpage.setVisible(true);
        dispose();
        
//            jFrameHomePage homepage = new jFrameHomePage();
//                homepage.setVisible(true);
//                jToggleBtngoBack.setText("Ahead >>");
//                dispose();
    }//GEN-LAST:event_jBtn_gobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_goback;
    private javax.swing.JButton jBtn_setup;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_dob;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_ages;
    private javax.swing.JTextField jTextField_dob;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
